# Prebuilt wasmtime C API for redpanda's WebAssembly data transforms.
#
# Upstream builds this with rules_rust's crate_universe, which needs network
# access to the crates.io index and therefore cannot run inside the build
# sandbox. The version and cargo features must track
# bazel/thirdparty/Cargo.toml in the redpanda source tree; it is deliberately
# not the top-level `wasmtime` package because redpanda pins an older major.
{
  lib,
  stdenv,
  rustPlatform,
  fetchFromGitHub,
  cmake,
}:
rustPlatform.buildRustPackage (finalAttrs: {
  pname = "wasmtime-c-api";
  version = "42.0.2";

  src = fetchFromGitHub {
    owner = "bytecodealliance";
    repo = "wasmtime";
    tag = "v${finalAttrs.version}";
    hash = "sha256-LfWnYZz5cmEP6eI92HCK7ATRE901L5c7sfIxn5VyHUc=";
    fetchSubmodules = true;
  };

  cargoHash = "sha256-b2zZVqQbPrtcbSk1oTiJqhwE1OczTTiLpRLNPFBpSE8=";

  auditable = false;

  nativeBuildInputs = [ cmake ];

  cargoBuildFlags = [
    "--package"
    "wasmtime-c-api"
  ];

  outputs = [
    "out"
    "dev"
  ];

  # Only the static library and headers are consumed.
  doCheck = false;

  installPhase =
    let
      inherit (stdenv.hostPlatform.rust) cargoShortTarget;
    in
    ''
      runHook preInstall

      install -Dm644 target/${cargoShortTarget}/release/libwasmtime.a $out/lib/libwasmtime.a
      # The C headers are generated by build.rs, so they only exist in the
      # cargo build directory.
      mkdir -p $dev
      cp -r target/${cargoShortTarget}/release/build/wasmtime-c-api-impl-*/out/include $dev/include

      runHook postInstall
    '';

  meta = {
    description = "Wasmtime C API static library for redpanda";
    homepage = "https://wasmtime.dev/";
    license = with lib.licenses; [
      asl20
      llvm-exception
    ];
    platforms = lib.platforms.linux;
  };
})
